// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4EPaS7Y706w04EJ1JcoZKQqxlRvMvpB8',
    appId: '1:423574108829:web:9cac045dbcd78e829f3274',
    messagingSenderId: '423574108829',
    projectId: 'kelimeoyunu-5a63a',
    authDomain: 'kelimeoyunu-5a63a.firebaseapp.com',
    storageBucket: 'kelimeoyunu-5a63a.appspot.com',
    measurementId: 'G-4KP584H0QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK89ikUUraEqpmZhD9BAVlfumQkfdkFYI',
    appId: '1:423574108829:android:8bc0ec3c972a4c2b9f3274',
    messagingSenderId: '423574108829',
    projectId: 'kelimeoyunu-5a63a',
    storageBucket: 'kelimeoyunu-5a63a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpumRcV6t4tQNfLVlkby6BT_esOYrDi3Q',
    appId: '1:423574108829:ios:47c83b34c2b191a09f3274',
    messagingSenderId: '423574108829',
    projectId: 'kelimeoyunu-5a63a',
    storageBucket: 'kelimeoyunu-5a63a.appspot.com',
    iosBundleId: 'com.may.yazlabkelimeoyunu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpumRcV6t4tQNfLVlkby6BT_esOYrDi3Q',
    appId: '1:423574108829:ios:01a76bc890ed94b29f3274',
    messagingSenderId: '423574108829',
    projectId: 'kelimeoyunu-5a63a',
    storageBucket: 'kelimeoyunu-5a63a.appspot.com',
    iosBundleId: 'com.example.yazlabkelimeoyunu.RunnerTests',
  );
}
